name: CI Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ main ]

jobs:
  truth-table-quality-gate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: csharp

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore TruthTable.slnx

      - name: Build project
        run: dotnet build TruthTable.slnx --no-restore --configuration Release -warnaserror

      - name: Run tests
        run: dotnet test TruthTable.slnx --no-build --configuration Release --verbosity normal
